name: Mirroring

on:
  push:
    branches:
    - master
  delete:
    branches:
    - master

jobs:
  to_vogsphere:
    runs-on: ubuntu-18.04
    steps:                                              # <-- must use actions/checkout@v1 before mirroring!
    - uses: actions/checkout@v1
    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          git@vogsphere-v2.42sp.org.br:vogsphere/intra-uuid-d43e9dcf-65f4-4ad1-84db-a6ecf9749df4-3655817
        ssh_private_key:                                # <-- use 'secrets' to pass credential information.
          ${{ secrets.FT_SSH_PRIVATE_KEY }}
